apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-api
  namespace: default
  labels:
    app: ims-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ims-api
  template:
    metadata:
      labels:
        app: ims-api
    spec:
      containers:
        - name: ims-api
          image: 974597802872.dkr.ecr.eu-central-1.amazonaws.com/imsapi:${BUILD_NUMBER}          
          ports:
            - containerPort: 5005
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          volumeMounts:
        - name: config-volume
          mountPath: /app/config     
      imagePullSecrets:
        - name: ax3-app
      volumes:
      - name: config-volume
        configMap:
          name: ims-appsettings.production